---
#
# Ansible managed
#
repository:
  description: Add custom services to your Linux system.
  homepage: https://buluma.github.io/
  topics: service, ansible, molecule, tox, playbook, hacktoberfest
